import 'prismjs/components/prism-abap.min';
import 'prismjs/components/prism-actionscript.min';
import 'prismjs/components/prism-ada.min';
import 'prismjs/components/prism-apacheconf.min';
import 'prismjs/components/prism-apl.min';
import 'prismjs/components/prism-applescript.min';
import 'prismjs/components/prism-arff.min';
import 'prismjs/components/prism-asciidoc.min';
import 'prismjs/components/prism-asm6502.min';
import 'prismjs/components/prism-aspnet.min';
import 'prismjs/components/prism-autohotkey.min';
import 'prismjs/components/prism-autoit.min';
import 'prismjs/components/prism-bash.min';
import 'prismjs/components/prism-basic.min';
import 'prismjs/components/prism-batch.min';
import 'prismjs/components/prism-c.min';
import 'prismjs/components/prism-bison.min';
import 'prismjs/components/prism-brainfuck.min';
import 'prismjs/components/prism-bro.min';
import 'prismjs/components/prism-clike.min';
import 'prismjs/components/prism-clojure.min';
import 'prismjs/components/prism-coffeescript.min';
import 'prismjs/components/prism-cpp.min';
import 'prismjs/components/prism-arduino.min';
import 'prismjs/components/prism-csharp.min';
import 'prismjs/components/prism-csp.min';
import 'prismjs/components/prism-css.min';
import 'prismjs/components/prism-css-extras.min';
import 'prismjs/components/prism-d.min';
import 'prismjs/components/prism-dart.min';
import 'prismjs/components/prism-diff.min';
import 'prismjs/components/prism-docker.min';
import 'prismjs/components/prism-eiffel.min';
import 'prismjs/components/prism-elixir.min';
import 'prismjs/components/prism-elm.min';
import 'prismjs/components/prism-erb.min';
import 'prismjs/components/prism-erlang.min';
import 'prismjs/components/prism-flow.min';
import 'prismjs/components/prism-fortran.min';
import 'prismjs/components/prism-fsharp.min';
import 'prismjs/components/prism-gedcom.min';
import 'prismjs/components/prism-gherkin.min';
import 'prismjs/components/prism-git.min';
import 'prismjs/components/prism-glsl.min';
import 'prismjs/components/prism-go.min';
import 'prismjs/components/prism-graphql.min';
import 'prismjs/components/prism-groovy.min';
import 'prismjs/components/prism-haml.min';
import 'prismjs/components/prism-handlebars.min';
import 'prismjs/components/prism-haskell.min';
import 'prismjs/components/prism-haxe.min';
import 'prismjs/components/prism-hpkp.min';
import 'prismjs/components/prism-hsts.min';
import 'prismjs/components/prism-http.min';
import 'prismjs/components/prism-ichigojam.min';
import 'prismjs/components/prism-icon.min';
import 'prismjs/components/prism-inform7.min';
import 'prismjs/components/prism-ini.min';
import 'prismjs/components/prism-io.min';
import 'prismjs/components/prism-j.min';
import 'prismjs/components/prism-java.min';
import 'prismjs/components/prism-javascript.min';
import 'prismjs/components/prism-jolie.min';
import 'prismjs/components/prism-json.min';
import 'prismjs/components/prism-jsx.min';
import 'prismjs/components/prism-julia.min';
import 'prismjs/components/prism-keyman.min';
import 'prismjs/components/prism-kotlin.min';
import 'prismjs/components/prism-latex.min';
import 'prismjs/components/prism-less.min';
import 'prismjs/components/prism-liquid.min';
import 'prismjs/components/prism-lisp.min';
import 'prismjs/components/prism-livescript.min';
import 'prismjs/components/prism-lolcode.min';
import 'prismjs/components/prism-lua.min';
import 'prismjs/components/prism-makefile.min';
import 'prismjs/components/prism-markdown.min';
import 'prismjs/components/prism-markup.min';
import 'prismjs/components/prism-markup-templating.min';
import 'prismjs/components/prism-django.min';
import 'prismjs/components/prism-matlab.min';
import 'prismjs/components/prism-mel.min';
import 'prismjs/components/prism-mizar.min';
import 'prismjs/components/prism-monkey.min';
import 'prismjs/components/prism-n4js.min';
import 'prismjs/components/prism-nasm.min';
import 'prismjs/components/prism-nginx.min';
import 'prismjs/components/prism-nim.min';
import 'prismjs/components/prism-nix.min';
import 'prismjs/components/prism-nsis.min';
import 'prismjs/components/prism-objectivec.min';
import 'prismjs/components/prism-ocaml.min';
import 'prismjs/components/prism-opencl.min';
import 'prismjs/components/prism-oz.min';
import 'prismjs/components/prism-parigp.min';
import 'prismjs/components/prism-parser.min';
import 'prismjs/components/prism-pascal.min';
import 'prismjs/components/prism-perl.min';
import 'prismjs/components/prism-php.min';
import 'prismjs/components/prism-php-extras.min';
import 'prismjs/components/prism-powershell.min';
import 'prismjs/components/prism-processing.min';
import 'prismjs/components/prism-prolog.min';
import 'prismjs/components/prism-properties.min';
import 'prismjs/components/prism-protobuf.min';
import 'prismjs/components/prism-pug.min';
import 'prismjs/components/prism-puppet.min';
import 'prismjs/components/prism-pure.min';
import 'prismjs/components/prism-python.min';
import 'prismjs/components/prism-q.min';
import 'prismjs/components/prism-qore.min';
import 'prismjs/components/prism-r.min';
import 'prismjs/components/prism-reason.min';
import 'prismjs/components/prism-renpy.min';
import 'prismjs/components/prism-rest.min';
import 'prismjs/components/prism-rip.min';
import 'prismjs/components/prism-roboconf.min';
import 'prismjs/components/prism-ruby.min';
import 'prismjs/components/prism-crystal.min';
import 'prismjs/components/prism-rust.min';
import 'prismjs/components/prism-sas.min';
import 'prismjs/components/prism-sass.min';
import 'prismjs/components/prism-scala.min';
import 'prismjs/components/prism-scheme.min';
import 'prismjs/components/prism-scss.min';
import 'prismjs/components/prism-smalltalk.min';
import 'prismjs/components/prism-smarty.min';
import 'prismjs/components/prism-soy.min';
import 'prismjs/components/prism-sql.min';
import 'prismjs/components/prism-plsql.min';
import 'prismjs/components/prism-stylus.min';
import 'prismjs/components/prism-swift.min';
import 'prismjs/components/prism-tap.min';
import 'prismjs/components/prism-tcl.min';
import 'prismjs/components/prism-textile.min';
import 'prismjs/components/prism-tsx.min';
import 'prismjs/components/prism-tt2.min';
import 'prismjs/components/prism-twig.min';
import 'prismjs/components/prism-typescript.min';
import 'prismjs/components/prism-vbnet.min';
import 'prismjs/components/prism-velocity.min';
import 'prismjs/components/prism-verilog.min';
import 'prismjs/components/prism-vhdl.min';
import 'prismjs/components/prism-vim.min';
import 'prismjs/components/prism-visual-basic.min';
import 'prismjs/components/prism-wasm.min';
import 'prismjs/components/prism-wiki.min';
import 'prismjs/components/prism-xeora.min';
import 'prismjs/components/prism-xojo.min';
import 'prismjs/components/prism-xquery.min';
import 'prismjs/components/prism-yaml.min';

export const prismLanguages: { [_: string]: string } = {
  properties: '.properties',
  asm6502: '6502 Assembly',
  abap: 'ABAP',
  apl: 'APL',
  arff: 'ARFF',
  aspnet: 'ASP.NET (C#)',
  actionscript: 'ActionScript',
  ada: 'Ada',
  apacheconf: 'Apache Configuration',
  applescript: 'AppleScript',
  arduino: 'Arduino',
  asciidoc: 'AsciiDoc',
  autohotkey: 'AutoHotkey',
  autoit: 'AutoIt',
  basic: 'BASIC',
  bash: 'Bash',
  batch: 'Batch',
  bison: 'Bison',
  brainfuck: 'Brainfuck',
  bro: 'Bro',
  c: 'C',
  csharp: 'C#',
  cpp: 'C++',
  clike: 'C-like',
  css: 'CSS',
  'css-extras': 'CSS Extras',
  clojure: 'Clojure',
  coffeescript: 'CoffeeScript',
  csp: 'Content-Security-Policy',
  crystal: 'Crystal',
  d: 'D',
  dart: 'Dart',
  diff: 'Diff',
  django: 'Django/Jinja2',
  docker: 'Docker',
  erb: 'ERB',
  eiffel: 'Eiffel',
  elixir: 'Elixir',
  elm: 'Elm',
  erlang: 'Erlang',
  fsharp: 'F#',
  flow: 'Flow',
  fortran: 'Fortran',
  gedcom: 'GEDCOM',
  glsl: 'GLSL',
  gml: 'GameMaker Language',
  gherkin: 'Gherkin',
  git: 'Git',
  go: 'Go',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  http: 'HTTP',
  hpkp: 'HTTP Public-Key-Pins',
  hsts: 'HTTP Strict-Transport-Security',
  haml: 'Haml',
  handlebars: 'Handlebars',
  haskell: 'Haskell',
  haxe: 'Haxe',
  ichigojam: 'IchigoJam',
  icon: 'Icon',
  inform7: 'Inform 7',
  ini: 'Ini',
  io: 'Io',
  j: 'J',
  json: 'JSON',
  java: 'Java',
  javascript: 'JavaScript',
  js: 'JavaScript',
  jolie: 'Jolie',
  julia: 'Julia',
  keyman: 'Keyman',
  kotlin: 'Kotlin',
  lolcode: 'LOLCODE',
  latex: 'LaTeX',
  less: 'Less',
  liquid: 'Liquid',
  lisp: 'Lisp',
  livescript: 'LiveScript',
  lua: 'Lua',
  matlab: 'MATLAB',
  mel: 'MEL',
  makefile: 'Makefile',
  markdown: 'Markdown',
  markup: 'Markup',
  'markup-templating': 'Markup templating',
  mizar: 'Mizar',
  monkey: 'Monkey',
  n4js: 'N4JS',
  nasm: 'NASM',
  nsis: 'NSIS',
  nim: 'Nim',
  nix: 'Nix',
  ocaml: 'OCaml',
  objectivec: 'Objective-C',
  opencl: 'OpenCL',
  oz: 'Oz',
  parigp: 'PARI/GP',
  php: 'PHP',
  'php-extras': 'PHP Extras',
  plsql: 'PL/SQL',
  parser: 'Parser',
  pascal: 'Pascal',
  perl: 'Perl',
  powershell: 'PowerShell',
  processing: 'Processing',
  prolog: 'Prolog',
  protobuf: 'Protocol Buffers',
  pug: 'Pug',
  puppet: 'Puppet',
  pure: 'Pure',
  python: 'Python',
  q: 'Q (kdb+ database)',
  qore: 'Qore',
  r: 'R',
  jsx: 'React JSX',
  tsx: 'React TSX',
  reason: 'Reason',
  renpy: "Ren'py",
  rip: 'Rip',
  roboconf: 'Roboconf',
  ruby: 'Ruby',
  rust: 'Rust',
  sas: 'SAS',
  sql: 'SQL',
  sass: 'Sass (Sass)',
  scss: 'Sass (Scss)',
  scala: 'Scala',
  scheme: 'Scheme',
  smalltalk: 'Smalltalk',
  smarty: 'Smarty',
  soy: 'Soy (Closure Template)',
  stylus: 'Stylus',
  swift: 'Swift',
  tap: 'TAP',
  tcl: 'Tcl',
  tt2: 'Template Toolkit 2',
  textile: 'Textile',
  twig: 'Twig',
  typescript: 'TypeScript',
  vbnet: 'VB.Net',
  vhdl: 'VHDL',
  velocity: 'Velocity',
  verilog: 'Verilog',
  'visual-basic': 'Visual Basic',
  wasm: 'WebAssembly',
  wiki: 'Wiki markup',
  xquery: 'XQuery',
  xeora: 'Xeora',
  xojo: 'Xojo (REALbasic)',
  yaml: 'YAML',
  nginx: 'nginx',
  rest: 'reST (reStructuredText)',
  vim: 'vim',
};
