name: Validate pull request
on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        with:
          # subject should not start with a capital letter or end with a period
          subjectPattern: ^(?![A-Z]).+(?<!\.)$
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            deprecation
          scopes: |
            changelog
            dev-infra
            migrations
            packaging
            release
            playground
            clipboard
            code-block
            media
            stache
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
